### ISSUE TITLE
Ansible installed from pengwin-setup gives "ModuleNotFoundError: No module named 'ansible'"

### ISSUE THREAD

**Issue by sbugalski** [WhitewaterFoundry/Pengwin#649]
**Describe the bug**

**To Reproduce**
1. Go to pengwin-setup
2. Choose tools > ANSIBLE
3. Install ansible
4. Execute ansible --version
5. See the error
```
ansible --version
Traceback (most recent call last):
  File "/usr/bin/ansible", line 34, in <module>
    from ansible import context
ModuleNotFoundError: No module named 'ansible'
```

**Expected behavior**
Properly working ansible

**Additional context**
Logs:
```
pengwin-setup
Starting pengwin-setup.
Updating package database
Running upgrade check...
Pengwin core package upgrades found
Holding pengwin-base & pengwin-setup to ensure no changes while operating
Selected: TOOLS
TOOLS
ANSIBLE
Installing ANSIBLE
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  distro-info-data ieee-data lsb-release python3-argcomplete python3-certifi python3-cffi-backend python3-chardet python3-crypto python3-cryptography python3-dnspython python3-httplib2 python3-idna
  python3-jinja2 python3-jmespath python3-kerberos python3-libcloud python3-lockfile python3-markupsafe python3-netaddr python3-ntlm-auth python3-requests python3-requests-kerberos
  python3-requests-ntlm python3-requests-toolbelt python3-selinux python3-simplejson python3-six python3-urllib3 python3-winrm python3-xmltodict
Suggested packages:
  cowsay sshpass python-cryptography-doc python3-cryptography-vectors python3-sniffio python3-trio python-jinja2-doc python-lockfile-doc ipython3 python-netaddr-docs python3-openssl python3-socks
  python-requests-doc
The following NEW packages will be installed:
  ansible distro-info-data ieee-data lsb-release python3-argcomplete python3-certifi python3-cffi-backend python3-chardet python3-crypto python3-cryptography python3-dnspython python3-httplib2
  python3-idna python3-jinja2 python3-jmespath python3-kerberos python3-libcloud python3-lockfile python3-markupsafe python3-netaddr python3-ntlm-auth python3-requests python3-requests-kerberos
  python3-requests-ntlm python3-requests-toolbelt python3-selinux python3-simplejson python3-six python3-urllib3 python3-winrm python3-xmltodict
0 upgraded, 31 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
Need to get 0 B/11.1 MB of archives.
After this operation, 99.5 MB of additional disk space will be used.
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package python3-cffi-backend.
(Reading database ... 76431 files and directories currently installed.)
Preparing to unpack .../00-python3-cffi-backend_1.14.3-2_amd64.deb ...
Unpacking python3-cffi-backend (1.14.3-2) ...
Selecting previously unselected package python3-six.
Preparing to unpack .../01-python3-six_1.15.0-1_all.deb ...
Unpacking python3-six (1.15.0-1) ...
Selecting previously unselected package python3-cryptography.
Preparing to unpack .../02-python3-cryptography_3.1-1+b1_amd64.deb ...
Unpacking python3-cryptography (3.1-1+b1) ...
Selecting previously unselected package python3-markupsafe.
Preparing to unpack .../03-python3-markupsafe_1.1.1-1+b2_amd64.deb ...
Unpacking python3-markupsafe (1.1.1-1+b2) ...
Selecting previously unselected package python3-jinja2.
Preparing to unpack .../04-python3-jinja2_2.11.2-1_all.deb ...
Unpacking python3-jinja2 (2.11.2-1) ...
Selecting previously unselected package python3-crypto.
Preparing to unpack .../05-python3-crypto_2.6.1-13.1+b2_amd64.deb ...
Unpacking python3-crypto (2.6.1-13.1+b2) ...
Selecting previously unselected package python3-dnspython.
Preparing to unpack .../06-python3-dnspython_2.0.0-1_all.deb ...
Unpacking python3-dnspython (2.0.0-1) ...
Selecting previously unselected package python3-httplib2.
Preparing to unpack .../07-python3-httplib2_0.18.1-1_all.deb ...
Unpacking python3-httplib2 (0.18.1-1) ...
Selecting previously unselected package ieee-data.
Preparing to unpack .../08-ieee-data_20180805.1_all.deb ...
Unpacking ieee-data (20180805.1) ...
Selecting previously unselected package python3-netaddr.
Preparing to unpack .../09-python3-netaddr_0.7.19-4_all.deb ...
Unpacking python3-netaddr (0.7.19-4) ...
Selecting previously unselected package ansible.
Preparing to unpack .../10-ansible_2.9.13+dfsg-1_all.deb ...
Unpacking ansible (2.9.13+dfsg-1) ...
Selecting previously unselected package distro-info-data.
Preparing to unpack .../11-distro-info-data_0.44_all.deb ...
Unpacking distro-info-data (0.44) ...
Selecting previously unselected package lsb-release.
Preparing to unpack .../12-lsb-release_11.1.0_all.deb ...
Unpacking lsb-release (11.1.0) ...
Selecting previously unselected package python3-argcomplete.
Preparing to unpack .../13-python3-argcomplete_1.8.1-1.3_all.deb ...
Unpacking python3-argcomplete (1.8.1-1.3) ...
Selecting previously unselected package python3-certifi.
Preparing to unpack .../14-python3-certifi_2020.6.20-1_all.deb ...
Unpacking python3-certifi (2020.6.20-1) ...
Selecting previously unselected package python3-chardet.
Preparing to unpack .../15-python3-chardet_3.0.4-7_all.deb ...
Unpacking python3-chardet (3.0.4-7) ...
Selecting previously unselected package python3-idna.
Preparing to unpack .../16-python3-idna_2.10-1_all.deb ...
Unpacking python3-idna (2.10-1) ...
Selecting previously unselected package python3-jmespath.
Preparing to unpack .../17-python3-jmespath_0.10.0-1_all.deb ...
Unpacking python3-jmespath (0.10.0-1) ...
Selecting previously unselected package python3-kerberos.
Preparing to unpack .../18-python3-kerberos_1.1.14-3.1+b2_amd64.deb ...
Unpacking python3-kerberos (1.1.14-3.1+b2) ...
Selecting previously unselected package python3-urllib3.
Preparing to unpack .../19-python3-urllib3_1.25.9-1_all.deb ...
Unpacking python3-urllib3 (1.25.9-1) ...
Selecting previously unselected package python3-requests.
Preparing to unpack .../20-python3-requests_2.23.0+dfsg-2_all.deb ...
Unpacking python3-requests (2.23.0+dfsg-2) ...
Selecting previously unselected package python3-lockfile.
Preparing to unpack .../21-python3-lockfile_1%3a0.12.2-2.2_all.deb ...
Unpacking python3-lockfile (1:0.12.2-2.2) ...
Selecting previously unselected package python3-simplejson.
Preparing to unpack .../22-python3-simplejson_3.17.0-1+b1_amd64.deb ...
Unpacking python3-simplejson (3.17.0-1+b1) ...
Selecting previously unselected package python3-libcloud.
Preparing to unpack .../23-python3-libcloud_3.2.0-1_all.deb ...
Unpacking python3-libcloud (3.2.0-1) ...
Selecting previously unselected package python3-ntlm-auth.
Preparing to unpack .../24-python3-ntlm-auth_1.4.0-1_all.deb ...
Unpacking python3-ntlm-auth (1.4.0-1) ...
Selecting previously unselected package python3-requests-kerberos.
Preparing to unpack .../25-python3-requests-kerberos_0.12.0-2_all.deb ...
Unpacking python3-requests-kerberos (0.12.0-2) ...
Selecting previously unselected package python3-requests-ntlm.
Preparing to unpack .../26-python3-requests-ntlm_1.1.0-1_all.deb ...
Unpacking python3-requests-ntlm (1.1.0-1) ...
Selecting previously unselected package python3-requests-toolbelt.
Preparing to unpack .../27-python3-requests-toolbelt_0.8.0-1.1_all.deb ...

Unpacking python3-requests-toolbelt (0.8.0-1.1) ...
Selecting previously unselected package python3-selinux.
Preparing to unpack .../28-python3-selinux_3.1-2+b1_amd64.deb ...
Unpacking python3-selinux (3.1-2+b1) ...
Selecting previously unselected package python3-xmltodict.
Preparing to unpack .../29-python3-xmltodict_0.12.0-2_all.deb ...
Unpacking python3-xmltodict (0.12.0-2) ...
Selecting previously unselected package python3-winrm.
Preparing to unpack .../30-python3-winrm_0.3.0-2_all.deb ...
Unpacking python3-winrm (0.3.0-2) ...
Setting up python3-lockfile (1:0.12.2-2.2) ...
Setting up distro-info-data (0.44) ...
Setting up python3-ntlm-auth (1.4.0-1) ...
Setting up x11-common (1:7.7+21) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: WARNING: No init system and policy-rc.d missing! Defaulting to block.
Setting up python3-markupsafe (1.1.1-1+b2) ...
Setting up tzdata (2020c-1) ...

Current default time zone: 'Europe/Warsaw'
Local time is now:      Fri Oct 23 12:04:16 CEST 2020.
Universal Time is now:  Fri Oct 23 10:04:16 UTC 2020.
Run 'dpkg-reconfigure tzdata' if you wish to change it.

Setting up python3-six (1.15.0-1) ...
Setting up python3-simplejson (3.17.0-1+b1) ...
Setting up python3-xmltodict (0.12.0-2) ...
Setting up python3-jinja2 (2.11.2-1) ...
Setting up python3-chardet (3.0.4-7) ...
Setting up python3-certifi (2020.6.20-1) ...
Setting up python3-jmespath (0.10.0-1) ...
Setting up python3-idna (2.10-1) ...
Setting up python3-urllib3 (1.25.9-1) ...
Setting up ieee-data (20180805.1) ...
Setting up python3-dnspython (2.0.0-1) ...
Setting up python3-selinux (3.1-2+b1) ...
Setting up python3-httplib2 (0.18.1-1) ...
Setting up python3-crypto (2.6.1-13.1+b2) ...
Setting up lsb-release (11.1.0) ...
Setting up python3-argcomplete (1.8.1-1.3) ...
Setting up python3-cffi-backend (1.14.3-2) ...
Setting up python3-kerberos (1.1.14-3.1+b2) ...
Setting up python3-cryptography (3.1-1+b1) ...
Setting up python3-requests (2.23.0+dfsg-2) ...
Setting up python3-requests-kerberos (0.12.0-2) ...
Setting up python3-netaddr (0.7.19-4) ...
Setting up ansible (2.9.13+dfsg-1) ...
Setting up python3-requests-ntlm (1.1.0-1) ...
Setting up python3-requests-toolbelt (0.8.0-1.1) ...
Setting up python3-libcloud (3.2.0-1) ...
Setting up python3-winrm (0.3.0-2) ...
Processing triggers for man-db (2.9.3-2) ...
Unholding pengwin-base & pengwin-setup
adm0n@sb-workstation:/mnt/c/Users/sb$ ansible --version
Traceback (most recent call last):
  File "/usr/bin/ansible", line 34, in <module>
    from ansible import context
ModuleNotFoundError: No module named 'ansible'
```

**Basic Troubleshooting Checklist**

[ ] I have searched Google for the error message.
[X] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[X] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[X] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[X] I have run Windows 10 updates and restarted.
[X] I have restarted WSL service: `wsl.exe --terminate WLinux` `wsl.exe --shutdown`.

What other troubleshooting have you attempted?

Insert here:

**Pengwin Version**

Run `grep "PENGWIN_VERSION" /etc/os-release` in Pengwin.

Insert here: 
```PENGWIN_VERSION="20.10.5"```

**WSL general info**

Run `wslsys` in Pengwin.

Insert here:
```wslsys
Parameter format not correct - ""
Parameter format not correct - ""
Parameter format not correct - ""
Parameter format not correct - ""
WSL Version: 2
Locale: pl_PL
Release Install Date: Tue Oct  6 10:07:21 CEST 2020
Branch: vb_release
Build: 19041
Full Build: 19041.1.amd64fre.vb_release.191206-1406
Display Scaling: 1
Windows Theme: dark
Windows Uptime: 0d 1h 26m
WSL Uptime: 0d 0h 35m
WSL Release: Pengwin
WSL Kernel: Linux
```

**Comment by crramirez** [comment]
Hello,

Thank you for reporting. We will check and get back to you.

Regards,
Carlos

**Comment by crramirez** [comment]
Hello,

Your installation may have some problems with the python environment. Two things:

1. I installed ansible with pengwin-setup without problems in a clean installation.
2. I see some Parameter format not correct - "" when you executed wslsys.

You can try installing ansible via pip. But I recommend if you can back up your home using pengwin-setup and then install pengwin from scratch.

```
sudo apt install python3-pip
pip uninstall ansible
python3 -m pip install --user ansible
```

Regards

**Comment by sbugalski** [comment]
> Hello,
> 
> Your installation may have some problems with the python environment. Two things:
> 
> 1. I installed ansible with pengwin-setup without problems in a clean installation.
> 2. I see some Parameter format not correct - "" when you executed wslsys.
> 
> You can try installing ansible via pip. But I recommend if you can back up your home using pengwin-setup and then install pengwin from scratch.
> 
> ```
> sudo apt install python3-pip
> pip uninstall ansible
> python3 -m pip install --user ansible
> ```
> 
> Regards

Thanks, it both sollutions worked.
